version: '3.9'
services:
  mysql:
    image: mysql:8.0.34
    container_name: mysql
    user: "${UID}:${GID}"
    environment:
      - MYSQL_DATABASE=practice_flatgeobuf
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./data/mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
