version: '3.9'
services:
  mysql:
    platform: linux/amd64
    image: mysql:8.0.33
    container_name: mysql
    # user: "${UID}:${GID}"
    user: mysql
    environment:
      - MYSQL_DATABASE=practice_flatgeobuf
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
